apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replica
  namespace: postgres-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        - secretRef:
            name: postgres-secrets
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        command:
        - "/bin/bash"
        - "-c"
        - |
          until pg_isready -h $PRIMARY_HOST -p 5432; do
            echo "Waiting for primary to be ready"
            sleep 2
          done
          pg_basebackup -h $PRIMARY_HOST -D $PGDATA -P -U $REPLICATION_USER -Fp -Xs -R
          exec docker-entrypoint.sh postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}