apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: postgres-cluster
spec:
  selector:
    app: postgres
    role: replica
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432