apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgres-cluster
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
  REPLICATION_PASSWORD: cmVwbF9wYXNzd29yZA==  # base64 encoded 'repl_password'